### ISSUE TITLE
Variable speed based on cpu usage?

### ISSUE THREAD

**Issue by steve02081504** [nikolat/ukagaka-party-parrot#1]
Like https://github.com/Kyome22/RunCat_for_windows, it would be interesting to add a pattern like this
And it would be nice to have a button to quickly set "always on top"!

**Comment by steve02081504** [comment]
Here are the ready-made saori: https://github.com/Taromati2/ghost/blob/1227eb6b3d39b87a95adbaa777ec4ac79500195b/master/saori/cpuusage.dll?raw=true
https://github.com/Taromati2/ghost/blob/1227eb6b3d39b87a95adbaa777ec4ac79500195b/master/dic/nurturance/nurturance.dic#L229
or c++ codes here
https://github.com/steve02081504/my-gists/commit/1dfaa0b8a1d1ccdd51a51c9668731e7c620a86d3

**Comment by nikolat** [comment]
I was actually inspired by the Party Parrot CPU meter.
https://forest.watch.impress.co.jp/docs/serial/yajiuma/1251932.html

The speed of the icon changes depending on the cpu usage.
But it's choppy, sorry.
I used ccpuid.dll from CSAORI to get the CPU usage rate, but thanks anyway.

**Comment by steve02081504** [comment]
What I was trying to achieve was to make the shell's animation speed vary according to cpu usage, haha
I'm still reading the source code of this ghost, maybe it's a bit difficult to implement this feature

Anyway, thanks

**Comment by steve02081504** [comment]
I would like to know what causes the lagging of the icon animation?
Does it sometimes lag on and off because ssp doesn't have a precise wait time?

**Comment by nikolat** [comment]
The OnSecondChange event used to perform the constant speed operation, but it is processed in a separate thread now.
This may have had an adverse effect.

**Comment by steve02081504** [comment]
Thanks, I understand
Good night!
